import { db, destinationsTable } from "@workspace/db";

const destinations = [
  {
    name: "Bali",
    country: "Indonesia",
    description: "A magical island paradise with ancient temples, lush rice terraces, stunning beaches, and world-class surf breaks. The spiritual heart of Southeast Asia.",
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    tags: ["beaches", "temples", "surf", "yoga", "nightlife"],
    costLevel: 1,
    climateType: "tropical",
    activityLevel: "moderate",
    travelTypes: ["beach", "culture", "nature", "party"],
    avgRating: 4.8,
  },
  {
    name: "Barcelona",
    country: "Spain",
    description: "A vibrant Mediterranean city where Gaudí's architecture meets golden beaches, world-renowned cuisine, and an electrifying nightlife scene that never sleeps.",
    imageUrl: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800&q=80",
    tags: ["architecture", "beaches", "food", "nightlife", "art"],
    costLevel: 2,
    climateType: "temperate",
    activityLevel: "moderate",
    travelTypes: ["culture", "beach", "party", "food"],
    avgRating: 4.7,
  },
  {
    name: "Tokyo",
    country: "Japan",
    description: "The world's most electrifying megacity — where ancient temples stand beside neon-lit skyscrapers, and Michelin-starred ramen shops hide in every alley.",
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
    tags: ["food", "technology", "culture", "shopping", "anime"],
    costLevel: 2,
    climateType: "temperate",
    activityLevel: "active",
    travelTypes: ["culture", "food", "adventure"],
    avgRating: 4.9,
  },
  {
    name: "Tulum",
    country: "Mexico",
    description: "Boho-chic beach paradise perched on Mayan ruins overlooking turquoise Caribbean waters, with cenotes to dive in and the best open-air parties in Latin America.",
    imageUrl: "https://images.unsplash.com/photo-1682685797507-d44d838b0ac7?w=800&q=80",
    tags: ["beaches", "ruins", "cenotes", "nightlife", "wellness"],
    costLevel: 2,
    climateType: "tropical",
    activityLevel: "moderate",
    travelTypes: ["beach", "culture", "party", "nature"],
    avgRating: 4.6,
  },
  {
    name: "Queenstown",
    country: "New Zealand",
    description: "The adrenaline capital of the world surrounded by jaw-dropping mountain scenery. Bungee jumping, skydiving, skiing, and glacier hiking in one stunning valley.",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    tags: ["adventure", "skiing", "bungee", "hiking", "scenery"],
    costLevel: 3,
    climateType: "temperate",
    activityLevel: "active",
    travelTypes: ["adventure", "nature"],
    avgRating: 4.8,
  },
  {
    name: "Santorini",
    country: "Greece",
    description: "The iconic whitewashed village above a volcanic caldera, with breathtaking sunsets over the Aegean Sea, volcanic beaches, and exceptional wines.",
    imageUrl: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80",
    tags: ["romance", "sunsets", "wine", "beaches", "views"],
    costLevel: 3,
    climateType: "hot",
    activityLevel: "chill",
    travelTypes: ["beach", "culture", "food"],
    avgRating: 4.7,
  },
  {
    name: "Medellín",
    country: "Colombia",
    description: "The city of eternal spring — once notorious, now one of South America's most innovative cities with a thriving art scene, incredible food, and amazing nightlife.",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    tags: ["nightlife", "art", "food", "culture", "history"],
    costLevel: 1,
    climateType: "tropical",
    activityLevel: "moderate",
    travelTypes: ["culture", "party", "food", "adventure"],
    avgRating: 4.5,
  },
  {
    name: "Lisbon",
    country: "Portugal",
    description: "Europe's sunniest capital, draped over seven hills above the Tagus river. Fado music, pastéis de nata, iconic trams, and a coastal vibe make it endlessly charming.",
    imageUrl: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80",
    tags: ["food", "history", "trams", "beaches", "fado"],
    costLevel: 2,
    climateType: "temperate",
    activityLevel: "moderate",
    travelTypes: ["culture", "food", "beach"],
    avgRating: 4.6,
  },
  {
    name: "Iceland",
    country: "Iceland",
    description: "Land of fire and ice — see the Northern Lights, soak in hot springs, hike on glaciers, and witness erupting volcanoes. Nature at its most dramatic.",
    imageUrl: "https://images.unsplash.com/photo-1531168556467-80aace0d0144?w=800&q=80",
    tags: ["northern lights", "glaciers", "hot springs", "hiking", "waterfalls"],
    costLevel: 3,
    climateType: "cold",
    activityLevel: "active",
    travelTypes: ["nature", "adventure"],
    avgRating: 4.8,
  },
  {
    name: "Bangkok",
    country: "Thailand",
    description: "A city of extremes — golden temples and street food at midnight, rooftop bars above the chaos, and the best shopping in Southeast Asia.",
    imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&q=80",
    tags: ["temples", "street food", "nightlife", "shopping", "party"],
    costLevel: 1,
    climateType: "tropical",
    activityLevel: "active",
    travelTypes: ["culture", "food", "party", "adventure"],
    avgRating: 4.5,
  },
  {
    name: "Patagonia",
    country: "Argentina/Chile",
    description: "The end of the world — raw, untamed wilderness of granite peaks, endless steppe, and calving glaciers. For those who want to feel truly small.",
    imageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    tags: ["hiking", "glaciers", "wildlife", "photography", "remote"],
    costLevel: 2,
    climateType: "cold",
    activityLevel: "active",
    travelTypes: ["nature", "adventure"],
    avgRating: 4.9,
  },
  {
    name: "Marrakech",
    country: "Morocco",
    description: "A sensory assault in the best possible way — vibrant souks, fragrant spice markets, stunning riads, and the legendary Djemaa el-Fna square.",
    imageUrl: "https://images.unsplash.com/photo-1597211833712-5e41faa202ea?w=800&q=80",
    tags: ["souks", "riads", "food", "culture", "desert"],
    costLevel: 1,
    climateType: "hot",
    activityLevel: "moderate",
    travelTypes: ["culture", "food", "adventure"],
    avgRating: 4.5,
  },
  {
    name: "Amalfi Coast",
    country: "Italy",
    description: "Clifftop villages tumbling into impossibly blue water, fresh-caught seafood, limoncello, and the most scenic coastal drive in the world.",
    imageUrl: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80",
    tags: ["coast", "food", "views", "boats", "romance"],
    costLevel: 3,
    climateType: "hot",
    activityLevel: "chill",
    travelTypes: ["beach", "food", "culture"],
    avgRating: 4.7,
  },
  {
    name: "Costa Rica",
    country: "Costa Rica",
    description: "Pure Life — cloud forests, active volcanoes, Pacific and Caribbean beaches all within hours of each other. Best for wildlife, surf, and zip-lining.",
    imageUrl: "https://images.unsplash.com/photo-1585464231875-d9ef1f5ad396?w=800&q=80",
    tags: ["wildlife", "surf", "volcanoes", "zip-line", "rainforest"],
    costLevel: 2,
    climateType: "tropical",
    activityLevel: "active",
    travelTypes: ["nature", "adventure", "beach"],
    avgRating: 4.6,
  },
  {
    name: "Amsterdam",
    country: "Netherlands",
    description: "Canal-laced city of cycling, museums, and incredible nightlife. Rembrandt to Rijksmuseum by day, legendary club scene by night.",
    imageUrl: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800&q=80",
    tags: ["canals", "museums", "cycling", "nightlife", "art"],
    costLevel: 2,
    climateType: "cold",
    activityLevel: "moderate",
    travelTypes: ["culture", "party", "food"],
    avgRating: 4.5,
  },
];

async function seed() {
  console.log("Seeding destinations...");

  const existing = await db.select().from(destinationsTable);
  if (existing.length > 0) {
    console.log(`${existing.length} destinations already exist, skipping seed.`);
    process.exit(0);
  }

  await db.insert(destinationsTable).values(destinations);
  console.log(`Inserted ${destinations.length} destinations.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
